### ISSUE TITLE
Virtual Cloud Desktop Using Apache Guacamole Proposed Changes

### ISSUE THREAD

**Issue by heavyimage** [linode/docs#2442] opened 2019-04-11 05:14 UTC
Link: https://linode.com/docs/applications/remote-desktop/remote-desktop-using-apache-guacamole-on-docker/

## Issue

The step where an ssh tunnel is created (ssh -L 5901:localhost:5901 -N -f -l user example.com
) is confusing and doesn't work for me (it says the port is already in use).  Where is this tunnel being created?  On which machine?  How can this tunnel be created if the VNC server is already using that port?

Thanks for any clarification!  I'm really excited about this tech and this guide :-)

**Comment by GuessWhoSamFoo** [comment] 2019-04-15 23:02
@heavyimage There might be an existing VNC connection to somewhere else. Either free up that port or start on 5902.

The tunnel should be created on the machine running the guacamole containers. This was recommended because authentication between guacamole and VNC was through an 8 character password. It's a good idea to take a look at the 1.0 release since there might be a better way now

**Comment by Guaris** [comment] 2019-04-17 12:40
Closing this. Please reopen if the issue is not resolved.

**Closed by Guaris** 2019-04-17 12:40 UTC
