### ISSUE TITLE
Run a Distribution-Supplied Kernel Proposed Changes

### ISSUE THREAD

**Issue by stvnjacobs** [linode/docs#1970] opened 2018-08-14 18:44 UTC
Link: https://linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel/

## Issue
The guide is titled "Run a Distribution-Supplied Kernel", but the documentation for "Recommended Distributions" instructs the reader on how to use the Linode kernel.

If the guide is in fact supposed to tell them how to use the Linode kernel, the following step is incorrect.

> To switch to the distro’s default kernel, select the latest Linode-supplied 64 bit kernel.

## Suggested Fix

Focus on directing the user to use GRUB 2 and the kernel provided by their distribution. (preferred)

_or_

Adjust the line to say this is to switch to the Linode kernel, as well as the example `uname` output.

**Comment by EdwardAngert** [comment] 2018-08-14 20:58
checking on whether this is covered by https://github.com/linode/docs/pull/1964

**Comment by cwlinode** [comment] 2018-09-25 16:21
PR 1964 linked to above significantly changes this guide since most distributions are Grub2 booting by default now. The cause for the original issue was removed. Closing.

**Closed by cwlinode** 2018-09-25 16:21 UTC
Labels: inaccurate guide
