### ISSUE TITLE
"Install Ruby on Rails with Apache on Debian 9" Installation Problem When Trying With Debian 10

### ISSUE THREAD

**Issue by JustinCEO** [linode/docs#2757] opened 2019-09-28 14:05 UTC
Link: https://linode.com/docs/development/ror/ruby-on-rails-apache-debian/
## Issue

I didn't see a guide for Debian 10, which I am using, so I tried to follow this guide. Everything went fine until the "Configure Apache to Work with Passenger" section, particular the section where it says: 

> sudo passenger-config about ruby-command
> Note
> Make sure that Passenger reports the version of Ruby that you installed with RVM. Normally `RVM uses paths similar to ~/.rvm/wrappers/ruby-X.X.X/ruby.`

On running `rvm current`, my ruby version reports as ruby-2.6.3, but Passenger seems to be using ruby 2.5.5p157

When I run `sudo passenger-config about ruby-command` I also get the following error:

```
Traceback (most recent call last):
        2: from /usr/bin/passenger-config:27:in `<main>'
        1: from /home/admin/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/admin/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- phusion_passenger (LoadError)
```

**Comment by Rajakavitha1** [comment] 2019-10-08 08:34
Hi @JustinCEO,

I tried the steps and I was not able to reproduce the error. However, the step that I did try the additional commands in step 5 (https://linode.com/docs/development/ror/ruby-on-rails-apache-debian/#install-rvm-and-ruby):
rvm install ruby-2.5.5
rvm --default use ruby-2.5.5 

Closing this issue for now. However, if you still encounter the problem please reopen the issue and provide us an update.

**Closed by Rajakavitha1** 2019-10-08 08:34 UTC
