### ISSUE TITLE
Docker install does not work with Ubuntu 16.04 LTS image

### ISSUE THREAD

**Issue by dwsteele** [linode/docs#480] opened 2016-05-31 17:58 UTC
I've tried a manual install from the Docker directions and also followed the directions here:

https://github.com/linode/docs/blob/master/docs/applications/containers/how-to-install-docker-and-deploy-a-lamp-stack.md

Either way the install locks at:

```
Setting up docker-engine (1.11.1-0~xenial) ...
```

Any idea if there are problems with 16.04? The same procedure works fine with 14.04.

**Comment by tonymke** [comment] 2016-06-07 23:41
Also experiencing this. Unsure what the issue is.

**Comment by alexfornuto** [comment] 2016-06-15 11:36
I belive that this has to do with a kernel option required in 16.04 and/or newer versions of Docker, but that's based only on what I've heard in passing. We'll look into this. Thanks for bringing it to our attention!

**Comment by tomschlick** [comment] 2016-06-17 18:32
I'm also seeing this same issue with it hanging on setup. Tried this guide but it didn't work for me http://lukeberndt.com/2016/getting-docker-up-on-linode-with-ubuntu-16-04/

Hopefully you guys can get this resolved soon! 👍

**Comment by ShakataGaNai** [comment] 2016-06-22 21:20
I've run across this issue as well, however I was working off the "manual" instructions from https://docs.docker.com/engine/installation/linux/ubuntulinux/ -- I've read in some places that the it requires you run a custom kernel so I followed https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm .  Unfortunately that didn't help either.

I can't find an exact cause but I think it might be related to https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1456789

**Comment by messense** [comment] 2016-07-03 09:59
Same issue.

**Comment by tomschlick** [comment] 2016-07-11 06:43
This worked for me (as mentioned in the docker issue):

```
sudo dmsetup mknodes
sudo apt-get install -y --reinstall docker-engine
```

**Comment by ericmok** [comment] 2016-07-13 21:20
I'm running Linux Kernel 4.6.4-040604-generic and my install also hangs the same way.
I followed @thaJeztah and @watchwithmike's instructions in https://github.com/docker/docker/issues/23968 to run the docker-engine using the overlay engine:

I created `/etc/docker/daemon.json` and put:
```
{
    "storage-driver": "overlay"
}
```

After restarting my computer, `sudo docker run hello-world` works and `sudo service docker status` shows it is actively running. I guess that means its working.

Also probably relevant to: https://github.com/docker/docker/issues/24478

**Comment by tiangolo** [comment] 2016-08-18 17:41
Cross posting my comment in https://github.com/docker/docker/issues/23347#issuecomment-240798701 as it might be useful for other people getting here.

For those of you running on Linode, @brentjanderson's instructions worked for me on a Ubuntu 16.04 as root user on a new Linode.

Namely:

* In a new Linode, update and upgrade packages:

```bash
apt-get update
apt-get upgrade -y
```

* Install and setup dmsetup:

```bash
apt-get install -y dmsetup
dmsetup mknodes
```

* Follow the [official installation instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

For example, as of now:

```bash
apt-get install apt-transport-https ca-certificates

apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list

apt-get update
apt-get install -y docker-engine
service docker start
```

**Comment by pbzona** [comment] 2017-02-23 21:36
I must have missed this issue while I was trying to fix Docker a while back. We've got the guide in a working state now (https://github.com/linode/docs/pull/575/files), using a Docker-maintained script for installation. 

@tiangolo's solution is preferable for Ubuntu installations (which this guide is), but the install script checks for distros, and should theoretically at least help users get Docker installed on other systems as well.

As such, I'm closing this issue. We're aware that the Docker guides need some love, but for now, things should be working. Thanks to all those who contributed here, and feel free to shoot us an email if you'd like to get involved in our Docker guide updates.

**Closed by pbzona** 2017-02-23 21:36 UTC
